### PR TITLE
Messages now also contain time of publishing and not just the date.

### PR DESCRIPTION
**Pull request by emildichmann272**
Remember to migrate the database before running the server.

### CODE REVIEW

**Comment by Notaduck** [comment]
I am ready to merge this, I just have one quick question.

Are we sure this works with Django `3.1.x`, it looks like you downgrade to `2.2.x`

**Comment by emildichmann272** [comment]
I wrote the migrating report myself such that I did not need to scrub the database, it is just an oversight in the copy paste structure I took off the web.

**Comment by emildichmann272** [comment]
And we should actually add the migration folder to the .gitignore since they would be different depending on when and on what commit you migrated.

**Comment by Notaduck** [comment]
I am going to add it right now in in the add_message branch.

**Pull request merged**
